apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-backend
  namespace: taskboard
  labels:
    app: taskboard-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskboard-backend
  template:
    metadata:
      labels:
        app: taskboard-backend
    spec:
      containers:
      - name: backend
        # Update this with your actual image
        image: your-registry/taskboard-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskboard-secrets
              key: db-password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: REDIS_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: taskboard-secrets
              key: jwt-secret
        - name: JWT_EXPIRY
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: JWT_EXPIRY
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: PORT
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: HOST
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: taskboard-config
              key: CORS_ORIGIN
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: taskboard-backend
  namespace: taskboard
  labels:
    app: taskboard-backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: taskboard-backend

