apiVersion: v1
kind: ConfigMap
metadata:
  name: taskboard-config
  namespace: taskboard
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "taskboard"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  JWT_EXPIRY: "24h"
  PORT: "8080"
  HOST: "0.0.0.0"
  # Update this with your actual frontend URL
  CORS_ORIGIN: "*"
  # Update this with your actual backend API URL
  REACT_APP_API_URL: "http://localhost:8080/api/v1"

